// <auto-generated />
using System;
using DesafioBaltaIO.Data.IBGE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioBaltaIO.Migrations
{
    [DbContext(typeof(IbgeDbContext))]
    [Migration("20231024162108_remapearColunaCidade")]
    partial class remapearColunaCidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DesafioBaltaIO.Domain.IBGE.Models.LocalidadeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CadastradoPor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar")
                        .HasDefaultValue("00000000-0000-0000-0000-000000000000");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime?>("DataEdicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("EditadoPor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar")
                        .HasDefaultValue("00000000-0000-0000-0000-000000000000");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Localidades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
